POST http://localhost:8080/events
Content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlZTJAZ21haWwuY29tIiwiZXhwIjoxNzIzMzU3MzUyLCJ1c2VySWQiOjV9.JJRHQv01ZNhy4-j6fXCbDHhWXH_3q9ANAH7ceYEEGxA

{
    "name": "Who",
    "description": "Urban party rave",
    "location": "Kaduna",
    "dateTime": "2024-01-04T15:30:00.000Z"
}