DELETE http://localhost:8080/events/5
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlZTJAZ21haWwuY29tIiwiZXhwIjoxNzIzMzU3MzUyLCJ1c2VySWQiOjV9.JJRHQv01ZNhy4-j6fXCbDHhWXH_3q9ANAH7ceYEEGxA
